### PR TITLE
Allow named arguments

### PR DESCRIPTION
**Pull request by meedstrom**
This allows you to write an anonymous lambda as

    (##(char) (< 767 char 818))

instead of the equivalent

    (##< 767 % 818)

It's a bit longer, but the ability to name arguments is pretty often something I appreciate as a documentation technique.  It's why I do so rarely reach for ## or fn.el or the like, and I'm averse to Dash macros like `--reject` unless I can fit the form on one line and it's quite clear from context what `it` means.

It's a bit of a funny story why this is a PR to llama.el, since I wasn't thinking of this codebase when I envisioned the `##(arg)` syntax, but as it happens, llama is squatting the ## namespace so there's nowhere else it could be implemented :)  Would you consider accepting this extension to the featureset?  I'm open to discuss the merits.

-----

This is actually a tiny change, just two lines.  The rest of the affected lines are indentation.  So you can close the PR and do it different if you prefer.

The new lines are

```elisp
  (if (proper-list-p fn)
      `(lambda ,fn ,@body)
    ...)
```

added at the start of the `llama` macro.

### CODE REVIEW

**Comment by tarsius** [comment]
> It's a bit of a funny story why this is a PR to llama.el, since I wasn't thinking of this codebase when I envisioned the `##(arg)` syntax, but as it happens, llama is squatting the ## namespace so there's nowhere else it could be implemented :) Would you consider accepting this extension to the featureset? I'm open to discuss the merits.

I have to be honest with you--the changes of me accepting this are tiny.

This is not an "extension to the featureset". Instead makes `##` revert back to (optionally) behave exactly like `lambda`, which IMO is pointless, because one could just use `lambda` instead:

```diff
-(##(char) (< 767 char 818))
+(lambda (char) (< 767 char 818))
```

It is possible to drop the space after `lambda`, and by enabling `prettify-symbols-mode`, you can get it to look like this:

```elisp
(λ(char) (< 767 char 818))
```

I am not 100% sure what you mean by "`##(arg)` syntax". Does this to refer to the `##(char)` portion in the code blocks you provided? Or do you work on actual new syntax, where `##` appears without a `(` in front of it?

**Comment by tarsius** [comment]
You could also

```elisp
(add-hook 'emacs-lisp-mode-hook
          (lambda () (setq prettify-symbols-alist '(("lambda"  . ?#)))))
```

To get it to look like

```elisp
(#(char) (< 767 char 818))
```

**Comment by meedstrom** [comment]
> I am not sure what you mean by "##(arg) syntax". Does this to the ##(char) portion in the code block you provided?

Yes.

Thank you for considering it. I realize it seems trivial. But the reason I originally quit using prettify (a long time ago) is that I want to use as big an editor font as possible.

There's a practical limit to how big you can make the font, which is determined by whether you can still fit two 80-column windows side by side.  And so my screen fits exactly that -- I don't get to make it any bigger, my hands are tied, but at least I *can* make it that big.  That has taught me to care about 79-char line maximums, and be grateful that so many people at least try to follow the principle, even though they probably didn't have my use case in mind.

If I use prettify, I benefit only myself. I get fooled about whether my lines really fit in 79 chars.

I agree that it's quite pointless to merely shorten "lambda " to "##" if shortening a line was the whole effect, but the length can create situations that limit your freedom to wrap lines in a logical way, so you have to wrap at an ugly point in order for a paragraph to fit in 79 chars.  Shortenings need to occur in the language IMO, ideally in its stdlib, not after-the-fact in individuals' editors.

Anyway, that's my justification. I understand you wouldn't feel like merging if you don't agree with these priorities.  Let me know and maybe I reconsider my priorities.

But you could consider it a way to popularize the syntax you want. Imagine `##(args)` attracts way more new users than `##fn`, and then `##fn` becomes more universally recognized by proxy.

**Comment by meedstrom** [comment]
I'll add that it does feel like nearly a non-issue, and yet. The triviality of the matter may be the reason we still have `lambda`.  I wouldn't roll out an entire package for the alias, nor argue for long on emacs-devel (maybe now I would). 

It's just close enough to acceptable, but it's not *good*.  The popularity of prettify shows that it is a thorn in people's eye, just not painful enough to compel much action.  One risks feeling like the detective Javert, who spent his career hunting down a thief who stole a loaf of bread. Why be the one to make a big fuss?

And yet. If I saw in Emacs 31 news that the ## shorthand is available, that'd be one of the big items.

It's normal these days for a language to have terse anonymous functions, like Javascript did away with `function` so you can just write `(arg1, arg2) => { frobnicate(arg1, arg2); }`.  That had technical reasons too, but I'll bet most users regarded it a benefit without knowing the technical reasons.  Somehow people find it ergonomic to avoid reading Latin characters (a problem with fn.el), maybe because it avoids subvocalization.

Llama looks like a natural place to slip it in, since then it actually serves dual purposes, unifying the syntax (sorta) with your *other* shorthand.

Apologies in advance -- it's easy to think of too many arguments in support :) I do not know if I'll agree with myself in six months, so I'll leave it at this.

**Comment by tarsius** [comment]
> [...] Apologies in advance -- it's easy to think of too many arguments in
> support :) I do not know if I'll agree with myself in six months, so
> I'll leave it at this.

I feel I have meet a kindred spirit.

Thanks for using this style of communication.

The changes of me merging this has somewhat gone up.  Like you, I will need time to make up my mind.  So for now I'll continue to work toward releasing v0.4.0, which will not include this.  Once that is done, there's one less uncertainty weighting on my mind, and I will be more free to consider this with an open mind.

**Comment by tarsius** [comment]
I am closing this to further reduce the pressure (put on by own zero-pr urge) to come to a decision.

**Comment by meedstrom** [comment]
Understandable. Have a good day.

**Comment by meedstrom** [comment]
FYI, I am okay if you never think about this again :) Would use in very few cases.

**Comment by tarsius** [comment]
You must made me think about it again! :grin:

Anyways... I still don't think this is a good fit and I am now going back to not thinking about it.

**Pull request closed without merging**
